version: '3.9'

services:
    backend:
        image: ezgas-backend
        build: .
        environment:
            DB_URI: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@database/ezgas?authSource=admin"
            API_SECRET: "${API_SECRET}"
            API_ORIGIN: "${API_ORIGIN}"
        ports:
            - ${BACKEND_PORT:-8080}:8080
        depends_on:
            - database

    database:
        image: mongo:4.4
        environment: 
            MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
            MONGO_INITDB_DATABASE: ezgas
        ports:
            - ${DATABASE_PORT:-27017}:27017
        volumes: 
            - database:/data/db
        command: ['--auth']

volumes:
    database:
        driver: local
