spring:
  data:
    mongodb:
      uri: 'mongodb://ezgas:12345@127.0.0.1/ezgas?authSource=admin'
      auto-index-creation: true

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

ezgas:
  api:
    key: 'apiKey'
    secret: '12345'
    origin: '*'
