spring:
  data:
    mongodb:
      host: 'localhost'
      database: 'ezgas'
      username: 'ezgas'
      password: '12345'

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

ezgas:
  api:
    key: 'apiKey'
    secret: '12345'
